"""add developer & analyst userrole

Revision ID: 1829a24adbfb
Revises: 2b489cdf6ff0
Create Date: 2025-09-05 00:06:30.114041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1829a24adbfb'
down_revision: Union[str, Sequence[str], None] = '2b489cdf6ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'DEVELOPER'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'ANALYST'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole DROP VALUE IF EXISTS 'DEVELOPER'")
    op.execute("ALTER TYPE userrole DROP VALUE IF EXISTS 'ANALYST'")
    # ### end Alembic commands ###
