"""personalisations indexes

Revision ID: 20d7fa647c5e
Revises: 370cd2a18b69
Create Date: 2025-09-05 03:32:38.728200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d7fa647c5e'
down_revision: Union[str, Sequence[str], None] = '370cd2a18b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_personalisations_experience_id'), table_name='personalisations')
    op.drop_index(op.f('idx_personalisations_priority'), table_name='personalisations')
    op.create_index('idx_personalisations_exp_active_priority', 'personalisations', ['experience_id', 'is_active', 'priority'], unique=False)
    op.create_index('idx_personalisations_org_app_search', 'personalisations', ['organisation_id', 'app_id', 'name', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_personalisations_org_app_search', table_name='personalisations')
    op.drop_index('idx_personalisations_exp_active_priority', table_name='personalisations')
    op.create_index(op.f('idx_personalisations_priority'), 'personalisations', ['priority'], unique=False)
    op.create_index(op.f('idx_personalisations_experience_id'), 'personalisations', ['experience_id'], unique=False)
    # ### end Alembic commands ###
