"""added roles

Revision ID: 2b489cdf6ff0
Revises: e43cccdcac6e
Create Date: 2025-08-15 08:11:52.191561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b489cdf6ff0'
down_revision: Union[str, Sequence[str], None] = 'e43cccdcac6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_apps_org_name', 'apps', ['organisation_id', 'name'], unique=False)
    op.create_index(op.f('ix_apps_organisation_id'), 'apps', ['organisation_id'], unique=False)
    op.create_unique_constraint('uq_org_app_name', 'apps', ['organisation_id', 'name'])
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_organisation_id'), 'auth_users', ['organisation_id'], unique=False)
    op.create_index('ix_invitations_email_org_status', 'invitations', ['email', 'organisation_id', 'status'], unique=False)
    op.create_index('ix_invitations_expires_status', 'invitations', ['expires_at', 'status'], unique=False)
    op.create_index('ix_invitations_org_status_created', 'invitations', ['organisation_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invitations_org_status_created', table_name='invitations')
    op.drop_index('ix_invitations_expires_status', table_name='invitations')
    op.drop_index('ix_invitations_email_org_status', table_name='invitations')
    op.drop_index(op.f('ix_auth_users_organisation_id'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_constraint('uq_org_app_name', 'apps', type_='unique')
    op.drop_index(op.f('ix_apps_organisation_id'), table_name='apps')
    op.drop_index('ix_apps_org_name', table_name='apps')
    # ### end Alembic commands ###
