"""reassign personalisation

Revision ID: 370cd2a18b69
Revises: 929afc1b3223
Create Date: 2025-09-05 02:48:36.961741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370cd2a18b69'
down_revision: Union[str, Sequence[str], None] = '929afc1b3223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalisations', sa.Column('reassign', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('idx_user_experience_main_query'), table_name='user_experience')
    op.drop_constraint(op.f('uq_user_experience_user_exp_org_app'), 'user_experience', type_='unique')
    op.create_index('idx_user_experience_user_org_app_exp_id', 'user_experience', ['user_id', 'organisation_id', 'app_id', 'experience_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_experience_user_org_app_exp_id', table_name='user_experience')
    op.create_unique_constraint(op.f('uq_user_experience_user_exp_org_app'), 'user_experience', ['user_id', 'experience_id', 'organisation_id', 'app_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_experience_main_query'), 'user_experience', ['user_id', 'organisation_id', 'app_id', 'experience_id'], unique=False)
    op.drop_column('personalisations', 'reassign')
    # ### end Alembic commands ###
