"""user profile keys

Revision ID: 3895c4350d44
Revises: cc00f8f5f444
Create Date: 2025-08-02 23:04:13.055190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3895c4350d44'
down_revision: Union[str, Sequence[str], None] = 'cc00f8f5f444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'organisation_id', 'app_id', name='uq_user_profile_keys_key_org_app')
    )
    op.create_index('idx_user_profile_keys_org_app', 'user_profile_keys', ['organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_user_profile_keys_id'), 'user_profile_keys', ['id'], unique=True)
    op.create_index(op.f('ix_user_profile_keys_pid'), 'user_profile_keys', ['pid'], unique=True)
    op.create_index('idx_events_schema_org_app', 'events_schema', ['organisation_id', 'app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_schema_org_app', table_name='events_schema')
    op.drop_index(op.f('ix_user_profile_keys_pid'), table_name='user_profile_keys')
    op.drop_index(op.f('ix_user_profile_keys_id'), table_name='user_profile_keys')
    op.drop_index('idx_user_profile_keys_org_app', table_name='user_profile_keys')
    op.drop_table('user_profile_keys')
    # ### end Alembic commands ###
