"""add key_type to api_keys

Revision ID: 4bc77d72f564
Revises: e6e640370561
Create Date: 2025-09-03 05:53:26.271200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc77d72f564'
down_revision: Union[str, Sequence[str], None] = 'e6e640370561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'key_type')
    # ### end Alembic commands ###
