"""user exp personalisation changes

Revision ID: 5262968b533c
Revises: 44a43d2daa5b
Create Date: 2025-07-18 22:02:59.620011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5262968b533c'
down_revision: Union[str, Sequence[str], None] = '44a43d2daa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience_segments', sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_experience_personalisation', sa.Column('segment_name', sa.String(), nullable=True))
    op.add_column('user_experience_personalisation', sa.Column('experience_segment_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('user_experience_personalisation_segment_id_fkey'), 'user_experience_personalisation', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_experience_personalisation_segment_id_fkey'), 'user_experience_personalisation', 'segments', ['segment_id'], ['pid'])
    op.drop_column('user_experience_personalisation', 'experience_segment_id')
    op.drop_column('user_experience_personalisation', 'segment_name')
    op.drop_column('experience_segments', 'last_updated_at')
    # ### end Alembic commands ###
