"""changes

Revision ID: 5fd807fce90a
Revises: 94f14e9ae245
Create Date: 2025-07-20 08:15:28.823899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fd807fce90a'
down_revision: Union[str, Sequence[str], None] = '94f14e9ae245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_feature_variants',
    sa.Column('personalisation_id', sa.UUID(), nullable=False),
    sa.Column('experience_feature_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_feature_id'], ['experience_features.pid'], ),
    sa.ForeignKeyConstraint(['personalisation_id'], ['personalisations.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_feature_variants_id'), 'experience_feature_variants', ['id'], unique=True)
    op.create_index(op.f('ix_experience_feature_variants_pid'), 'experience_feature_variants', ['pid'], unique=True)
    op.drop_index(op.f('ix_personalisation_feature_variants_id'), table_name='personalisation_feature_variants')
    op.drop_index(op.f('ix_personalisation_feature_variants_pid'), table_name='personalisation_feature_variants')
    op.drop_table('personalisation_feature_variants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalisation_feature_variants',
    sa.Column('personalisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('experience_feature_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experience_feature_id'], ['experience_features.pid'], name=op.f('personalisation_feature_variants_experience_feature_id_fkey')),
    sa.ForeignKeyConstraint(['personalisation_id'], ['personalisations.pid'], name=op.f('personalisation_feature_variants_personalisation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('personalisation_feature_variants_pkey'))
    )
    op.create_index(op.f('ix_personalisation_feature_variants_pid'), 'personalisation_feature_variants', ['pid'], unique=True)
    op.create_index(op.f('ix_personalisation_feature_variants_id'), 'personalisation_feature_variants', ['id'], unique=True)
    op.drop_index(op.f('ix_experience_feature_variants_pid'), table_name='experience_feature_variants')
    op.drop_index(op.f('ix_experience_feature_variants_id'), table_name='experience_feature_variants')
    op.drop_table('experience_feature_variants')
    # ### end Alembic commands ###
