"""index changes

Revision ID: 6a0f06261d5f
Revises: 4a1010eebfbd
Create Date: 2025-07-15 16:13:22.169223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0f06261d5f'
down_revision: Union[str, Sequence[str], None] = '4a1010eebfbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feature_variants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=True),
    sa.Column('variant_name', sa.String(), nullable=False),
    sa.Column('variant_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature_id', 'organisation_id', 'app_id', name='uq_user_feature_variants_user_feature_org_app')
    )
    op.create_index('idx_user_feature_variants_experience', 'user_feature_variants', ['experience_id', 'organisation_id', 'app_id'], unique=False)
    op.create_index('idx_user_feature_variants_feature_org_app', 'user_feature_variants', ['feature_id', 'organisation_id', 'app_id'], unique=False)
    op.create_index('idx_user_feature_variants_org_app', 'user_feature_variants', ['organisation_id', 'app_id'], unique=False)
    op.create_index('idx_user_feature_variants_user_feature', 'user_feature_variants', ['user_id', 'feature_id'], unique=False)
    op.create_index('idx_user_feature_variants_user_org_app', 'user_feature_variants', ['user_id', 'organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_user_feature_variants_id'), 'user_feature_variants', ['id'], unique=True)
    op.create_index(op.f('ix_user_feature_variants_pid'), 'user_feature_variants', ['pid'], unique=True)
    op.drop_index(op.f('idx_experience_segments_experience'), table_name='experience_segments')
    op.drop_index(op.f('idx_experience_segments_segment'), table_name='experience_segments')
    op.drop_index(op.f('ix_experience_segments_experience_id'), table_name='experience_segments')
    op.drop_index(op.f('ix_experience_segments_segment_id'), table_name='experience_segments')
    op.create_index('idx_experience_segments_experience_id', 'experience_segments', ['experience_id'], unique=False)
    op.create_index('idx_experience_segments_segment_id', 'experience_segments', ['segment_id'], unique=False)
    op.drop_index(op.f('ix_experiences_app_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_last_updated_at'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_name'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_organisation_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_priority'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_status'), table_name='experiences')
    op.create_index('idx_experiences_name_org_app', 'experiences', ['name', 'organisation_id', 'app_id'], unique=False)
    op.create_index('idx_experiences_org_app', 'experiences', ['organisation_id', 'app_id'], unique=False)
    op.create_unique_constraint('uq_experiences_priority_org_app', 'experiences', ['priority', 'organisation_id', 'app_id'])
    op.drop_index(op.f('ix_feature_flags_app_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_name'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_organisation_id'), table_name='feature_flags')
    op.create_index('idx_feature_flags_org_app', 'feature_flags', ['organisation_id', 'app_id'], unique=False)
    op.drop_index(op.f('ix_feature_variants_experience_id'), table_name='feature_variants')
    op.drop_index(op.f('ix_feature_variants_feature_id'), table_name='feature_variants')
    op.drop_index(op.f('ix_feature_variants_name'), table_name='feature_variants')
    op.create_index('idx_feature_variants_experience_id', 'feature_variants', ['experience_id'], unique=False)
    op.create_index('idx_feature_variants_feature_id', 'feature_variants', ['feature_id'], unique=False)
    op.create_unique_constraint('uq_feature_variants_feature_experience', 'feature_variants', ['feature_id', 'experience_id'])
    op.drop_index(op.f('idx_feature_variants_templates_feature'), table_name='feature_variants_templates')
    op.drop_index(op.f('ix_feature_variants_templates_feature_id'), table_name='feature_variants_templates')
    op.drop_index(op.f('ix_feature_variants_templates_name'), table_name='feature_variants_templates')
    op.create_index('idx_feature_variants_templates_feature_id', 'feature_variants_templates', ['feature_id'], unique=False)
    op.drop_index(op.f('idx_segments_name_org_app'), table_name='segments')
    op.drop_index(op.f('ix_segments_app_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_name'), table_name='segments')
    op.drop_index(op.f('ix_segments_organisation_id'), table_name='segments')
    op.create_index('idx_segments_org_app', 'segments', ['organisation_id', 'app_id'], unique=False)
    op.add_column('user_experience', sa.Column('organisation_id', sa.String(), nullable=False))
    op.add_column('user_experience', sa.Column('app_id', sa.String(), nullable=False))
    op.drop_index(op.f('idx_user_experience_assigned'), table_name='user_experience')
    op.drop_index(op.f('idx_user_experience_experience'), table_name='user_experience')
    op.drop_index(op.f('idx_user_experience_user'), table_name='user_experience')
    op.drop_index(op.f('ix_user_experience_experience_id'), table_name='user_experience')
    op.drop_index(op.f('ix_user_experience_user_id'), table_name='user_experience')
    op.create_index('idx_user_experience_assigned_org_app', 'user_experience', ['assigned_at', 'organisation_id', 'app_id'], unique=False)
    op.create_index('idx_user_experience_experience_org_app', 'user_experience', ['experience_id', 'organisation_id', 'app_id'], unique=False)
    op.create_index('idx_user_experience_org_app', 'user_experience', ['organisation_id', 'app_id'], unique=False)
    op.create_index('idx_user_experience_user_assigned', 'user_experience', ['user_id', 'assigned_at'], unique=False)
    op.create_index('idx_user_experience_user_org_app', 'user_experience', ['user_id', 'organisation_id', 'app_id'], unique=False)
    op.drop_index(op.f('ix_users_app_id'), table_name='users')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index('idx_users_org_app', 'users', ['organisation_id', 'app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_org_app', table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_users_app_id'), 'users', ['app_id'], unique=False)
    op.drop_index('idx_user_experience_user_org_app', table_name='user_experience')
    op.drop_index('idx_user_experience_user_assigned', table_name='user_experience')
    op.drop_index('idx_user_experience_org_app', table_name='user_experience')
    op.drop_index('idx_user_experience_experience_org_app', table_name='user_experience')
    op.drop_index('idx_user_experience_assigned_org_app', table_name='user_experience')
    op.create_index(op.f('ix_user_experience_user_id'), 'user_experience', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_experience_experience_id'), 'user_experience', ['experience_id'], unique=False)
    op.create_index(op.f('idx_user_experience_user'), 'user_experience', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_experience_experience'), 'user_experience', ['experience_id'], unique=False)
    op.create_index(op.f('idx_user_experience_assigned'), 'user_experience', ['assigned_at'], unique=False)
    op.drop_column('user_experience', 'app_id')
    op.drop_column('user_experience', 'organisation_id')
    op.drop_index('idx_segments_org_app', table_name='segments')
    op.create_index(op.f('ix_segments_organisation_id'), 'segments', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_segments_name'), 'segments', ['name'], unique=False)
    op.create_index(op.f('ix_segments_app_id'), 'segments', ['app_id'], unique=False)
    op.create_index(op.f('idx_segments_name_org_app'), 'segments', ['name', 'organisation_id', 'app_id'], unique=False)
    op.drop_index('idx_feature_variants_templates_feature_id', table_name='feature_variants_templates')
    op.create_index(op.f('ix_feature_variants_templates_name'), 'feature_variants_templates', ['name'], unique=False)
    op.create_index(op.f('ix_feature_variants_templates_feature_id'), 'feature_variants_templates', ['feature_id'], unique=False)
    op.create_index(op.f('idx_feature_variants_templates_feature'), 'feature_variants_templates', ['feature_id'], unique=False)
    op.drop_constraint('uq_feature_variants_feature_experience', 'feature_variants', type_='unique')
    op.drop_index('idx_feature_variants_feature_id', table_name='feature_variants')
    op.drop_index('idx_feature_variants_experience_id', table_name='feature_variants')
    op.create_index(op.f('ix_feature_variants_name'), 'feature_variants', ['name'], unique=False)
    op.create_index(op.f('ix_feature_variants_feature_id'), 'feature_variants', ['feature_id'], unique=False)
    op.create_index(op.f('ix_feature_variants_experience_id'), 'feature_variants', ['experience_id'], unique=False)
    op.drop_index('idx_feature_flags_org_app', table_name='feature_flags')
    op.create_index(op.f('ix_feature_flags_organisation_id'), 'feature_flags', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_feature_flags_name'), 'feature_flags', ['name'], unique=False)
    op.create_index(op.f('ix_feature_flags_app_id'), 'feature_flags', ['app_id'], unique=False)
    op.drop_constraint('uq_experiences_priority_org_app', 'experiences', type_='unique')
    op.drop_index('idx_experiences_org_app', table_name='experiences')
    op.drop_index('idx_experiences_name_org_app', table_name='experiences')
    op.create_index(op.f('ix_experiences_status'), 'experiences', ['status'], unique=False)
    op.create_index(op.f('ix_experiences_priority'), 'experiences', ['priority'], unique=False)
    op.create_index(op.f('ix_experiences_organisation_id'), 'experiences', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_experiences_name'), 'experiences', ['name'], unique=False)
    op.create_index(op.f('ix_experiences_last_updated_at'), 'experiences', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_experiences_app_id'), 'experiences', ['app_id'], unique=False)
    op.drop_index('idx_experience_segments_segment_id', table_name='experience_segments')
    op.drop_index('idx_experience_segments_experience_id', table_name='experience_segments')
    op.create_index(op.f('ix_experience_segments_segment_id'), 'experience_segments', ['segment_id'], unique=False)
    op.create_index(op.f('ix_experience_segments_experience_id'), 'experience_segments', ['experience_id'], unique=False)
    op.create_index(op.f('idx_experience_segments_segment'), 'experience_segments', ['segment_id'], unique=False)
    op.create_index(op.f('idx_experience_segments_experience'), 'experience_segments', ['experience_id'], unique=False)
    op.drop_index(op.f('ix_user_feature_variants_pid'), table_name='user_feature_variants')
    op.drop_index(op.f('ix_user_feature_variants_id'), table_name='user_feature_variants')
    op.drop_index('idx_user_feature_variants_user_org_app', table_name='user_feature_variants')
    op.drop_index('idx_user_feature_variants_user_feature', table_name='user_feature_variants')
    op.drop_index('idx_user_feature_variants_org_app', table_name='user_feature_variants')
    op.drop_index('idx_user_feature_variants_feature_org_app', table_name='user_feature_variants')
    op.drop_index('idx_user_feature_variants_experience', table_name='user_feature_variants')
    op.drop_table('user_feature_variants')
    # ### end Alembic commands ###
