"""feature flag description added

Revision ID: 6a3689eca2f9
Revises: bfe2f9b73949
Create Date: 2025-07-12 02:15:26.880497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3689eca2f9'
down_revision: Union[str, Sequence[str], None] = 'bfe2f9b73949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flags', sa.Column('description', sa.String(), server_default='', nullable=False))
    op.create_index(op.f('ix_feature_flags_description'), 'feature_flags', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_flags_description'), table_name='feature_flags')
    op.drop_column('feature_flags', 'description')
    # ### end Alembic commands ###
