"""personalisations is_default

Revision ID: 6af3d9b07e6d
Revises: b05f76cebc88
Create Date: 2025-07-17 03:00:42.705310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af3d9b07e6d'
down_revision: Union[str, Sequence[str], None] = 'b05f76cebc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalisations', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personalisations', 'is_default')
    # ### end Alembic commands ###
