"""create segments

Revision ID: 812918eb453c
Revises: f23b53e54d73
Create Date: 2025-07-15 03:03:13.968484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812918eb453c'
down_revision: Union[str, Sequence[str], None] = 'f23b53e54d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('rule_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_app_id'), 'segments', ['app_id'], unique=False)
    op.create_index(op.f('ix_segments_id'), 'segments', ['id'], unique=True)
    op.create_index(op.f('ix_segments_name'), 'segments', ['name'], unique=False)
    op.create_index(op.f('ix_segments_organisation_id'), 'segments', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_segments_pid'), 'segments', ['pid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_pid'), table_name='segments')
    op.drop_index(op.f('ix_segments_organisation_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_name'), table_name='segments')
    op.drop_index(op.f('ix_segments_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_app_id'), table_name='segments')
    op.drop_table('segments')
    # ### end Alembic commands ###
