"""add is_active to personalisations

Revision ID: 929afc1b3223
Revises: 1829a24adbfb
Create Date: 2025-08-27 15:31:06.823044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929afc1b3223'
down_revision: Union[str, Sequence[str], None] = '1829a24adbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalisations', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personalisations', 'is_active')
    # ### end Alembic commands ###
