"""remove relationships

Revision ID: 93376d7e42ab
Revises: bff6523735f0
Create Date: 2025-07-15 02:46:58.337622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93376d7e42ab'
down_revision: Union[str, Sequence[str], None] = 'bff6523735f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_feature_variants', sa.Column('variant_name', sa.String(), nullable=False))
    op.add_column('user_feature_variants', sa.Column('variant_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False))
    op.drop_index(op.f('idx_user_feature_variants_variant_id'), table_name='user_feature_variants')
    op.drop_index(op.f('ix_user_feature_variants_variant_id'), table_name='user_feature_variants')
    op.create_index('idx_user_feature_variants_variant_name', 'user_feature_variants', ['variant_name'], unique=False)
    op.create_index(op.f('ix_user_feature_variants_variant_name'), 'user_feature_variants', ['variant_name'], unique=False)
    op.drop_constraint(op.f('user_feature_variants_variant_id_fkey'), 'user_feature_variants', type_='foreignkey')
    op.drop_constraint(op.f('user_feature_variants_feature_id_fkey'), 'user_feature_variants', type_='foreignkey')
    op.drop_constraint(op.f('user_feature_variants_user_id_fkey'), 'user_feature_variants', type_='foreignkey')
    op.drop_column('user_feature_variants', 'variant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_feature_variants', sa.Column('variant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_feature_variants_user_id_fkey'), 'user_feature_variants', 'users', ['user_id'], ['pid'])
    op.create_foreign_key(op.f('user_feature_variants_feature_id_fkey'), 'user_feature_variants', 'feature_flags', ['feature_id'], ['pid'])
    op.create_foreign_key(op.f('user_feature_variants_variant_id_fkey'), 'user_feature_variants', 'feature_variants', ['variant_id'], ['pid'])
    op.drop_index(op.f('ix_user_feature_variants_variant_name'), table_name='user_feature_variants')
    op.drop_index('idx_user_feature_variants_variant_name', table_name='user_feature_variants')
    op.create_index(op.f('ix_user_feature_variants_variant_id'), 'user_feature_variants', ['variant_id'], unique=False)
    op.create_index(op.f('idx_user_feature_variants_variant_id'), 'user_feature_variants', ['variant_id'], unique=False)
    op.drop_column('user_feature_variants', 'variant_config')
    op.drop_column('user_feature_variants', 'variant_name')
    # ### end Alembic commands ###
