"""init

Revision ID: 94f14e9ae245
Revises: 
Create Date: 2025-07-20 03:59:38.666141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f14e9ae245'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rule_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', 'app_id', name='uq_campaigns_name_org_app')
    )
    op.create_index('idx_campaigns_org_app', 'campaigns', ['organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=True)
    op.create_index(op.f('ix_campaigns_pid'), 'campaigns', ['pid'], unique=True)
    op.create_table('experiences',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', 'app_id', name='uq_experiences_name_org_app')
    )
    op.create_index('idx_experiences_name_org_app', 'experiences', ['name', 'organisation_id', 'app_id'], unique=False)
    op.create_index('idx_experiences_org_app', 'experiences', ['organisation_id', 'app_id'], unique=False)
    op.create_index('idx_experiences_status_org_app', 'experiences', ['status', 'organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=True)
    op.create_index(op.f('ix_experiences_pid'), 'experiences', ['pid'], unique=True)
    op.create_table('feature_flags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('keys_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', 'app_id', name='uq_feature_flags_name_org_app')
    )
    op.create_index('idx_feature_flags_active_org_app', 'feature_flags', ['is_active', 'organisation_id', 'app_id'], unique=False)
    op.create_index('idx_feature_flags_org_app', 'feature_flags', ['organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=True)
    op.create_index(op.f('ix_feature_flags_pid'), 'feature_flags', ['pid'], unique=True)
    op.create_table('metrics',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_name_org_app', 'metrics', ['name', 'organisation_id', 'app_id'], unique=False)
    op.create_index('idx_metrics_org_app', 'metrics', ['organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=True)
    op.create_index(op.f('ix_metrics_pid'), 'metrics', ['pid'], unique=True)
    op.create_table('segments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('rule_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', 'app_id', name='uq_segments_name_org_app')
    )
    op.create_index('idx_segments_org_app', 'segments', ['organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_segments_id'), 'segments', ['id'], unique=True)
    op.create_index(op.f('ix_segments_pid'), 'segments', ['pid'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_profile', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organisation_id', 'app_id', name='uq_users_user_id_org_app')
    )
    op.create_index('idx_users_org_app', 'users', ['organisation_id', 'app_id'], unique=False)
    op.create_index('idx_users_user_id_org_app', 'users', ['user_id', 'organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_pid'), 'users', ['pid'], unique=True)
    op.create_table('experience_features',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.pid'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['feature_flags.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'feature_id', name='uq_experience_features_exp_feat')
    )
    op.create_index('idx_experience_features_experience_id', 'experience_features', ['experience_id'], unique=False)
    op.create_index('idx_experience_features_feature_flag_id', 'experience_features', ['feature_id'], unique=False)
    op.create_index(op.f('ix_experience_features_id'), 'experience_features', ['id'], unique=True)
    op.create_index(op.f('ix_experience_features_pid'), 'experience_features', ['pid'], unique=True)
    op.create_table('experience_metrics',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.pid'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'metric_id', name='uq_experience_metrics_exp_metric')
    )
    op.create_index(op.f('ix_experience_metrics_experience_id'), 'experience_metrics', ['experience_id'], unique=False)
    op.create_index(op.f('ix_experience_metrics_id'), 'experience_metrics', ['id'], unique=True)
    op.create_index(op.f('ix_experience_metrics_metric_id'), 'experience_metrics', ['metric_id'], unique=False)
    op.create_index(op.f('ix_experience_metrics_pid'), 'experience_metrics', ['pid'], unique=True)
    op.create_table('personalisations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'experience_id', name='uq_personalisations_name_exp')
    )
    op.create_index('idx_personalisations_experience_id', 'personalisations', ['experience_id'], unique=False)
    op.create_index(op.f('ix_personalisations_id'), 'personalisations', ['id'], unique=True)
    op.create_index(op.f('ix_personalisations_pid'), 'personalisations', ['pid'], unique=True)
    op.create_table('targeting_rules',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('target_percentage', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'priority', name='uq_targeting_rules_exp_prio')
    )
    op.create_index('idx_targeting_rules_experience_id', 'targeting_rules', ['experience_id'], unique=False)
    op.create_index('idx_targeting_rules_priority', 'targeting_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_targeting_rules_id'), 'targeting_rules', ['id'], unique=True)
    op.create_index(op.f('ix_targeting_rules_pid'), 'targeting_rules', ['pid'], unique=True)
    op.create_table('personalisation_feature_variants',
    sa.Column('personalisation_id', sa.UUID(), nullable=False),
    sa.Column('experience_feature_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_feature_id'], ['experience_features.pid'], ),
    sa.ForeignKeyConstraint(['personalisation_id'], ['personalisations.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personalisation_feature_variants_id'), 'personalisation_feature_variants', ['id'], unique=True)
    op.create_index(op.f('ix_personalisation_feature_variants_pid'), 'personalisation_feature_variants', ['pid'], unique=True)
    op.create_table('personalisation_metrics',
    sa.Column('personalisation_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.pid'], ),
    sa.ForeignKeyConstraint(['personalisation_id'], ['personalisations.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personalisation_id', 'metric_id', name='uq_personalisation_metrics_pers_metric')
    )
    op.create_index(op.f('ix_personalisation_metrics_id'), 'personalisation_metrics', ['id'], unique=True)
    op.create_index(op.f('ix_personalisation_metrics_metric_id'), 'personalisation_metrics', ['metric_id'], unique=False)
    op.create_index(op.f('ix_personalisation_metrics_personalisation_id'), 'personalisation_metrics', ['personalisation_id'], unique=False)
    op.create_index(op.f('ix_personalisation_metrics_pid'), 'personalisation_metrics', ['pid'], unique=True)
    op.create_table('targeting_rule_metrics',
    sa.Column('targeting_rule_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.pid'], ),
    sa.ForeignKeyConstraint(['targeting_rule_id'], ['targeting_rules.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('targeting_rule_id', 'metric_id', name='uq_experience_segment_metrics_tr_metric')
    )
    op.create_index(op.f('ix_targeting_rule_metrics_id'), 'targeting_rule_metrics', ['id'], unique=True)
    op.create_index(op.f('ix_targeting_rule_metrics_metric_id'), 'targeting_rule_metrics', ['metric_id'], unique=False)
    op.create_index(op.f('ix_targeting_rule_metrics_pid'), 'targeting_rule_metrics', ['pid'], unique=True)
    op.create_index(op.f('ix_targeting_rule_metrics_targeting_rule_id'), 'targeting_rule_metrics', ['targeting_rule_id'], unique=False)
    op.create_table('targeting_rule_personalisations',
    sa.Column('targeting_rule_id', sa.UUID(), nullable=False),
    sa.Column('personalisation_id', sa.UUID(), nullable=False),
    sa.Column('target_percentage', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personalisation_id'], ['personalisations.pid'], ),
    sa.ForeignKeyConstraint(['targeting_rule_id'], ['targeting_rules.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targeting_rule_personalisations_id'), 'targeting_rule_personalisations', ['id'], unique=True)
    op.create_index(op.f('ix_targeting_rule_personalisations_personalisation_id'), 'targeting_rule_personalisations', ['personalisation_id'], unique=False)
    op.create_index(op.f('ix_targeting_rule_personalisations_pid'), 'targeting_rule_personalisations', ['pid'], unique=True)
    op.create_table('targeting_rule_segments',
    sa.Column('targeting_rule_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.pid'], ),
    sa.ForeignKeyConstraint(['targeting_rule_id'], ['targeting_rules.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('targeting_rule_id', 'segment_id', name='uq_targeting_rule_segments_tr_seg')
    )
    op.create_index('idx_targeting_rule_segments_segment_id', 'targeting_rule_segments', ['segment_id'], unique=False)
    op.create_index('idx_targeting_rule_segments_targeting_rule_id', 'targeting_rule_segments', ['targeting_rule_id'], unique=False)
    op.create_index(op.f('ix_targeting_rule_segments_id'), 'targeting_rule_segments', ['id'], unique=True)
    op.create_index(op.f('ix_targeting_rule_segments_pid'), 'targeting_rule_segments', ['pid'], unique=True)
    op.create_table('user_experience_personalisation',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('personalisation_id', sa.UUID(), nullable=True),
    sa.Column('segment_name', sa.String(), nullable=True),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('experience_segment_id', sa.UUID(), nullable=True),
    sa.Column('experience_segment_personalisation_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evaluation_reason', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.pid'], ),
    sa.ForeignKeyConstraint(['personalisation_id'], ['personalisations.pid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'experience_id', 'organisation_id', 'app_id', name='uq_user_experience_user_exp_org_app')
    )
    op.create_index('idx_user_experience_assigned_org_app', 'user_experience_personalisation', ['assigned_at', 'organisation_id', 'app_id'], unique=False)
    op.create_index('idx_user_experience_experience_org_app', 'user_experience_personalisation', ['experience_id', 'organisation_id', 'app_id'], unique=False)
    op.create_index('idx_user_experience_main_query', 'user_experience_personalisation', ['user_id', 'organisation_id', 'app_id', 'experience_id'], unique=False)
    op.create_index('idx_user_experience_user_assigned', 'user_experience_personalisation', ['user_id', 'assigned_at'], unique=False)
    op.create_index(op.f('ix_user_experience_personalisation_id'), 'user_experience_personalisation', ['id'], unique=True)
    op.create_index(op.f('ix_user_experience_personalisation_pid'), 'user_experience_personalisation', ['pid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_experience_personalisation_pid'), table_name='user_experience_personalisation')
    op.drop_index(op.f('ix_user_experience_personalisation_id'), table_name='user_experience_personalisation')
    op.drop_index('idx_user_experience_user_assigned', table_name='user_experience_personalisation')
    op.drop_index('idx_user_experience_main_query', table_name='user_experience_personalisation')
    op.drop_index('idx_user_experience_experience_org_app', table_name='user_experience_personalisation')
    op.drop_index('idx_user_experience_assigned_org_app', table_name='user_experience_personalisation')
    op.drop_table('user_experience_personalisation')
    op.drop_index(op.f('ix_targeting_rule_segments_pid'), table_name='targeting_rule_segments')
    op.drop_index(op.f('ix_targeting_rule_segments_id'), table_name='targeting_rule_segments')
    op.drop_index('idx_targeting_rule_segments_targeting_rule_id', table_name='targeting_rule_segments')
    op.drop_index('idx_targeting_rule_segments_segment_id', table_name='targeting_rule_segments')
    op.drop_table('targeting_rule_segments')
    op.drop_index(op.f('ix_targeting_rule_personalisations_pid'), table_name='targeting_rule_personalisations')
    op.drop_index(op.f('ix_targeting_rule_personalisations_personalisation_id'), table_name='targeting_rule_personalisations')
    op.drop_index(op.f('ix_targeting_rule_personalisations_id'), table_name='targeting_rule_personalisations')
    op.drop_table('targeting_rule_personalisations')
    op.drop_index(op.f('ix_targeting_rule_metrics_targeting_rule_id'), table_name='targeting_rule_metrics')
    op.drop_index(op.f('ix_targeting_rule_metrics_pid'), table_name='targeting_rule_metrics')
    op.drop_index(op.f('ix_targeting_rule_metrics_metric_id'), table_name='targeting_rule_metrics')
    op.drop_index(op.f('ix_targeting_rule_metrics_id'), table_name='targeting_rule_metrics')
    op.drop_table('targeting_rule_metrics')
    op.drop_index(op.f('ix_personalisation_metrics_pid'), table_name='personalisation_metrics')
    op.drop_index(op.f('ix_personalisation_metrics_personalisation_id'), table_name='personalisation_metrics')
    op.drop_index(op.f('ix_personalisation_metrics_metric_id'), table_name='personalisation_metrics')
    op.drop_index(op.f('ix_personalisation_metrics_id'), table_name='personalisation_metrics')
    op.drop_table('personalisation_metrics')
    op.drop_index(op.f('ix_personalisation_feature_variants_pid'), table_name='personalisation_feature_variants')
    op.drop_index(op.f('ix_personalisation_feature_variants_id'), table_name='personalisation_feature_variants')
    op.drop_table('personalisation_feature_variants')
    op.drop_index(op.f('ix_targeting_rules_pid'), table_name='targeting_rules')
    op.drop_index(op.f('ix_targeting_rules_id'), table_name='targeting_rules')
    op.drop_index('idx_targeting_rules_priority', table_name='targeting_rules')
    op.drop_index('idx_targeting_rules_experience_id', table_name='targeting_rules')
    op.drop_table('targeting_rules')
    op.drop_index(op.f('ix_personalisations_pid'), table_name='personalisations')
    op.drop_index(op.f('ix_personalisations_id'), table_name='personalisations')
    op.drop_index('idx_personalisations_experience_id', table_name='personalisations')
    op.drop_table('personalisations')
    op.drop_index(op.f('ix_experience_metrics_pid'), table_name='experience_metrics')
    op.drop_index(op.f('ix_experience_metrics_metric_id'), table_name='experience_metrics')
    op.drop_index(op.f('ix_experience_metrics_id'), table_name='experience_metrics')
    op.drop_index(op.f('ix_experience_metrics_experience_id'), table_name='experience_metrics')
    op.drop_table('experience_metrics')
    op.drop_index(op.f('ix_experience_features_pid'), table_name='experience_features')
    op.drop_index(op.f('ix_experience_features_id'), table_name='experience_features')
    op.drop_index('idx_experience_features_feature_flag_id', table_name='experience_features')
    op.drop_index('idx_experience_features_experience_id', table_name='experience_features')
    op.drop_table('experience_features')
    op.drop_index(op.f('ix_users_pid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_users_user_id_org_app', table_name='users')
    op.drop_index('idx_users_org_app', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_segments_pid'), table_name='segments')
    op.drop_index(op.f('ix_segments_id'), table_name='segments')
    op.drop_index('idx_segments_org_app', table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_metrics_pid'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index('idx_metrics_org_app', table_name='metrics')
    op.drop_index('idx_metrics_name_org_app', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_feature_flags_pid'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_index('idx_feature_flags_org_app', table_name='feature_flags')
    op.drop_index('idx_feature_flags_active_org_app', table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_experiences_pid'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_index('idx_experiences_status_org_app', table_name='experiences')
    op.drop_index('idx_experiences_org_app', table_name='experiences')
    op.drop_index('idx_experiences_name_org_app', table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_campaigns_pid'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index('idx_campaigns_org_app', table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
