"""campaigns

Revision ID: 96a7a1c6813c
Revises: ae9bbf1eeb8e
Create Date: 2025-07-16 12:26:03.169130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a7a1c6813c'
down_revision: Union[str, Sequence[str], None] = 'ae9bbf1eeb8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rule_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', 'app_id', name='uq_campaigns_name_org_app')
    )
    op.create_index('idx_campaigns_org_app', 'campaigns', ['organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=True)
    op.create_index(op.f('ix_campaigns_pid'), 'campaigns', ['pid'], unique=True)
    op.add_column('experiences', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'experiences', 'campaigns', ['campaign_id'], ['pid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_column('experiences', 'campaign_id')
    op.drop_index(op.f('ix_campaigns_pid'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index('idx_campaigns_org_app', table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
