"""refactor_campaigns_experiences_many_to_many

Revision ID: a43052eed194
Revises: 96a7a1c6813c
Create Date: 2025-07-16 12:56:02.203111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43052eed194'
down_revision: Union[str, Sequence[str], None] = '96a7a1c6813c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_campaigns',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.pid'], ),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'campaign_id', name='uq_experience_campaigns_exp_camp')
    )
    op.create_index('idx_experience_campaigns_campaign_id', 'experience_campaigns', ['campaign_id'], unique=False)
    op.create_index('idx_experience_campaigns_created_at', 'experience_campaigns', ['created_at'], unique=False)
    op.create_index('idx_experience_campaigns_experience_id', 'experience_campaigns', ['experience_id'], unique=False)
    op.create_index(op.f('ix_experience_campaigns_id'), 'experience_campaigns', ['id'], unique=True)
    op.create_index(op.f('ix_experience_campaigns_pid'), 'experience_campaigns', ['pid'], unique=True)
    op.drop_constraint(op.f('experiences_campaign_id_fkey'), 'experiences', type_='foreignkey')
    op.drop_column('experiences', 'campaign_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('experiences_campaign_id_fkey'), 'experiences', 'campaigns', ['campaign_id'], ['pid'])
    op.drop_index(op.f('ix_experience_campaigns_pid'), table_name='experience_campaigns')
    op.drop_index(op.f('ix_experience_campaigns_id'), table_name='experience_campaigns')
    op.drop_index('idx_experience_campaigns_experience_id', table_name='experience_campaigns')
    op.drop_index('idx_experience_campaigns_created_at', table_name='experience_campaigns')
    op.drop_index('idx_experience_campaigns_campaign_id', table_name='experience_campaigns')
    op.drop_table('experience_campaigns')
    # ### end Alembic commands ###
