"""changes

Revision ID: ae9bbf1eeb8e
Revises: 6a0f06261d5f
Create Date: 2025-07-16 00:35:07.480937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9bbf1eeb8e'
down_revision: Union[str, Sequence[str], None] = '6a0f06261d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_feature_variants', sa.Column('variant_assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_feature_variants', 'variant_assigned_at')
    # ### end Alembic commands ###
