"""personalisation variants map

Revision ID: b05f76cebc88
Revises: 753ccdc8f39f
Create Date: 2025-07-17 01:26:59.565384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05f76cebc88'
down_revision: Union[str, Sequence[str], None] = '753ccdc8f39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalisation_feature_variants',
    sa.Column('personalisation_id', sa.UUID(), nullable=False),
    sa.Column('feature_variant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_variant_id'], ['feature_variants.pid'], ),
    sa.ForeignKeyConstraint(['personalisation_id'], ['personalisations.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personalisation_feature_variants_id'), 'personalisation_feature_variants', ['id'], unique=True)
    op.create_index(op.f('ix_personalisation_feature_variants_pid'), 'personalisation_feature_variants', ['pid'], unique=True)
    op.drop_constraint(op.f('feature_variants_personalisation_id_fkey'), 'feature_variants', type_='foreignkey')
    op.drop_column('feature_variants', 'personalisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_variants', sa.Column('personalisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('feature_variants_personalisation_id_fkey'), 'feature_variants', 'personalisations', ['personalisation_id'], ['pid'])
    op.drop_index(op.f('ix_personalisation_feature_variants_pid'), table_name='personalisation_feature_variants')
    op.drop_index(op.f('ix_personalisation_feature_variants_id'), table_name='personalisation_feature_variants')
    op.drop_table('personalisation_feature_variants')
    # ### end Alembic commands ###
