"""query removed

Revision ID: b6ae24620e69
Revises: 16c7bebaec9f
Create Date: 2025-07-19 09:31:19.620661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ae24620e69'
down_revision: Union[str, Sequence[str], None] = '16c7bebaec9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'query')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
