"""default variant added

Revision ID: bfe2f9b73949
Revises: 66020925153f
Create Date: 2025-07-12 01:27:55.755147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe2f9b73949'
down_revision: Union[str, Sequence[str], None] = '66020925153f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flags', sa.Column('default_variant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_feature_flags_default_variant_id'), 'feature_flags', ['default_variant_id'], unique=False)
    op.create_foreign_key(None, 'feature_flags', 'feature_variants', ['default_variant_id'], ['pid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feature_flags', type_='foreignkey')
    op.drop_index(op.f('ix_feature_flags_default_variant_id'), table_name='feature_flags')
    op.drop_column('feature_flags', 'default_variant_id')
    # ### end Alembic commands ###
