"""keys config changes

Revision ID: bff6523735f0
Revises: 4c34a5d9aee7
Create Date: 2025-07-15 00:51:11.009577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff6523735f0'
down_revision: Union[str, Sequence[str], None] = '4c34a5d9aee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flags', sa.Column('keys_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False))
    op.drop_index(op.f('ix_feature_flags_default_variant_id'), table_name='feature_flags')
    op.drop_constraint(op.f('feature_flags_default_variant_id_fkey'), 'feature_flags', type_='foreignkey')
    op.drop_column('feature_flags', 'default_variant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flags', sa.Column('default_variant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('feature_flags_default_variant_id_fkey'), 'feature_flags', 'feature_variants', ['default_variant_id'], ['pid'])
    op.create_index(op.f('ix_feature_flags_default_variant_id'), 'feature_flags', ['default_variant_id'], unique=False)
    op.drop_column('feature_flags', 'keys_config')
    # ### end Alembic commands ###
