"""add reassign flag & drop user_experience unique constraint

Revision ID: de6e635935c2
Revises: 929afc1b3223
Create Date: 2025-08-29 17:12:05.607942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6e635935c2'
down_revision: Union[str, Sequence[str], None] = '929afc1b3223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalisations', sa.Column('reassign', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('uq_user_experience_user_exp_org_app'), 'user_experience', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_experience_user_exp_org_app'), 'user_experience', ['user_id', 'experience_id', 'organisation_id', 'app_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('personalisations', 'reassign')
    # ### end Alembic commands ###
