"""personalisations organisation

Revision ID: e20204923f06
Revises: 5fd807fce90a
Create Date: 2025-07-20 08:59:28.041470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20204923f06'
down_revision: Union[str, Sequence[str], None] = '5fd807fce90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalisations', sa.Column('organisation_id', sa.String(), nullable=False))
    op.add_column('personalisations', sa.Column('app_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personalisations', 'app_id')
    op.drop_column('personalisations', 'organisation_id')
    # ### end Alembic commands ###
