"""target percentage

Revision ID: e4478a07e51e
Revises: a43052eed194
Create Date: 2025-07-16 13:25:04.071792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4478a07e51e'
down_revision: Union[str, Sequence[str], None] = 'a43052eed194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience_campaigns', sa.Column('target_percentage', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_experience_campaigns_created_at'), table_name='experience_campaigns')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_experience_campaigns_created_at'), 'experience_campaigns', ['created_at'], unique=False)
    op.drop_column('experience_campaigns', 'target_percentage')
    # ### end Alembic commands ###
