"""api key constraint

Revision ID: e6e640370561
Revises: 2530b7439876
Create Date: 2025-09-02 05:03:14.117862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e640370561'
down_revision: Union[str, Sequence[str], None] = '2530b7439876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_api_keys_name_org_app', 'api_keys', ['name', 'organisation_id', 'app_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_api_keys_name_org_app', 'api_keys', type_='unique')
    # ### end Alembic commands ###
