"""init

Revision ID: f23b53e54d73
Revises: 
Create Date: 2025-07-15 02:54:08.900833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23b53e54d73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('keys_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', 'app_id', name='uq_feature_flags_name_org_app')
    )
    op.create_index('idx_feature_flags_active_org_app', 'feature_flags', ['is_active', 'organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_feature_flags_app_id'), 'feature_flags', ['app_id'], unique=False)
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=True)
    op.create_index(op.f('ix_feature_flags_name'), 'feature_flags', ['name'], unique=False)
    op.create_index(op.f('ix_feature_flags_organisation_id'), 'feature_flags', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_feature_flags_pid'), 'feature_flags', ['pid'], unique=True)
    op.create_table('user_feature_variants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('variant_name', sa.String(), nullable=False),
    sa.Column('variant_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature_id', name='uq_user_feature_variants_user_feature')
    )
    op.create_index('idx_user_feature_variants_org_app', 'user_feature_variants', ['organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_user_feature_variants_app_id'), 'user_feature_variants', ['app_id'], unique=False)
    op.create_index(op.f('ix_user_feature_variants_feature_id'), 'user_feature_variants', ['feature_id'], unique=False)
    op.create_index(op.f('ix_user_feature_variants_id'), 'user_feature_variants', ['id'], unique=True)
    op.create_index(op.f('ix_user_feature_variants_organisation_id'), 'user_feature_variants', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_user_feature_variants_pid'), 'user_feature_variants', ['pid'], unique=True)
    op.create_index(op.f('ix_user_feature_variants_user_id'), 'user_feature_variants', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_feature_variants_variant_name'), 'user_feature_variants', ['variant_name'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_profile', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organisation_id', 'app_id', name='uq_users_user_id_org_app')
    )
    op.create_index('idx_users_user_id_org_app', 'users', ['user_id', 'organisation_id', 'app_id'], unique=False)
    op.create_index(op.f('ix_users_app_id'), 'users', ['app_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_users_pid'), 'users', ['pid'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('feature_variants',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature_flags.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'feature_id', name='uq_feature_variants_name_feature')
    )
    op.create_index(op.f('ix_feature_variants_feature_id'), 'feature_variants', ['feature_id'], unique=False)
    op.create_index(op.f('ix_feature_variants_id'), 'feature_variants', ['id'], unique=True)
    op.create_index(op.f('ix_feature_variants_name'), 'feature_variants', ['name'], unique=False)
    op.create_index(op.f('ix_feature_variants_pid'), 'feature_variants', ['pid'], unique=True)
    op.create_table('individual_targeting',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('rule_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature_flags.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_targeting_feature_id'), 'individual_targeting', ['feature_id'], unique=False)
    op.create_index(op.f('ix_individual_targeting_id'), 'individual_targeting', ['id'], unique=True)
    op.create_index(op.f('ix_individual_targeting_pid'), 'individual_targeting', ['pid'], unique=True)
    op.create_table('targeting_rules',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('rule_config', sa.JSON(), server_default=sa.text("json('{}')"), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature_flags.pid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id', 'priority', name='uq_targeting_rules_feature_priority')
    )
    op.create_index('idx_targeting_rules_feature_priority', 'targeting_rules', ['feature_id', 'priority'], unique=False)
    op.create_index(op.f('ix_targeting_rules_feature_id'), 'targeting_rules', ['feature_id'], unique=False)
    op.create_index(op.f('ix_targeting_rules_id'), 'targeting_rules', ['id'], unique=True)
    op.create_index(op.f('ix_targeting_rules_pid'), 'targeting_rules', ['pid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_targeting_rules_pid'), table_name='targeting_rules')
    op.drop_index(op.f('ix_targeting_rules_id'), table_name='targeting_rules')
    op.drop_index(op.f('ix_targeting_rules_feature_id'), table_name='targeting_rules')
    op.drop_index('idx_targeting_rules_feature_priority', table_name='targeting_rules')
    op.drop_table('targeting_rules')
    op.drop_index(op.f('ix_individual_targeting_pid'), table_name='individual_targeting')
    op.drop_index(op.f('ix_individual_targeting_id'), table_name='individual_targeting')
    op.drop_index(op.f('ix_individual_targeting_feature_id'), table_name='individual_targeting')
    op.drop_table('individual_targeting')
    op.drop_index(op.f('ix_feature_variants_pid'), table_name='feature_variants')
    op.drop_index(op.f('ix_feature_variants_name'), table_name='feature_variants')
    op.drop_index(op.f('ix_feature_variants_id'), table_name='feature_variants')
    op.drop_index(op.f('ix_feature_variants_feature_id'), table_name='feature_variants')
    op.drop_table('feature_variants')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_pid'), table_name='users')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_app_id'), table_name='users')
    op.drop_index('idx_users_user_id_org_app', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_feature_variants_variant_name'), table_name='user_feature_variants')
    op.drop_index(op.f('ix_user_feature_variants_user_id'), table_name='user_feature_variants')
    op.drop_index(op.f('ix_user_feature_variants_pid'), table_name='user_feature_variants')
    op.drop_index(op.f('ix_user_feature_variants_organisation_id'), table_name='user_feature_variants')
    op.drop_index(op.f('ix_user_feature_variants_id'), table_name='user_feature_variants')
    op.drop_index(op.f('ix_user_feature_variants_feature_id'), table_name='user_feature_variants')
    op.drop_index(op.f('ix_user_feature_variants_app_id'), table_name='user_feature_variants')
    op.drop_index('idx_user_feature_variants_org_app', table_name='user_feature_variants')
    op.drop_table('user_feature_variants')
    op.drop_index(op.f('ix_feature_flags_pid'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_organisation_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_name'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_app_id'), table_name='feature_flags')
    op.drop_index('idx_feature_flags_active_org_app', table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
