"""add history table

Revision ID: f5cccd3ee090
Revises: b2e022ac685e
Create Date: 2025-09-02 02:04:14.502685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cccd3ee090'
down_revision: Union[str, Sequence[str], None] = 'de6e635935c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_log',
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_log_id'), 'history_log', ['id'], unique=True)
    op.create_index(op.f('ix_history_log_object_id'), 'history_log', ['object_id'], unique=False)
    op.create_index(op.f('ix_history_log_pid'), 'history_log', ['pid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_log_pid'), table_name='history_log')
    op.drop_index(op.f('ix_history_log_object_id'), table_name='history_log')
    op.drop_index(op.f('ix_history_log_id'), table_name='history_log')
    op.drop_table('history_log')
    # ### end Alembic commands ###
